@uid=shopppon@gmail.com

POST /v1/{uid}/logs HTTP/1.1
Host: 127.0.0.1:8000
Content-Type: application/json

{
    "log": {
        "action": "foo",
        "content": "bar",
        "stack": "fuzzy",
        "platform": "macos"
    }
}
