name: fclipboard
description: Fuzzy search by title and copy to clipboard.
publish_to: "none"
version: 0.3.0

environment:
  sdk: ">=3.0.0-339.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  fuzzy: <1.0.0
  yaml: ^3.1.1
  path: ^1.8.0
  path_provider: ^2.0.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.2.2
  sqlite3_flutter_libs: ^0.5.16
  hotkey_manager: ^0.1.7
  window_manager: ^0.3.1
  fluttertoast: ^8.2.1
  emoji_picker_flutter: ^1.5.2
  http: ^0.13.3
  json_schema: ^5.1.2
  sn_progress_dialog: ^1.1.3
  collection: ^1.17.1
  file_picker: ^5.3.1
  json_annotation: ^4.8.1
  package_info_plus: ^4.0.2
  flutter_web_auth_2: ^2.0.0
  sign_in_with_apple: ^5.0.0
  shared_preferences: ^2.2.1
  logger: ^2.0.2
  openapi:
    path: ./apis/out/dart/

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: # added
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.6.2
  build_runner: ^2.3.3
  test: ^1.24.6

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/schemas/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/fclipboard.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/fclipboard-transparent.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/fclipboard-transparent.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/fclipboard-transparent.png"

flutter_intl:
  enabled: true
