name: fclipboard
description: Fuzzy search by title and copy to clipboard.
publish_to: "none"
version: 0.2.4

environment:
  sdk: ">=3.0.0-339.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  fuzzy: <1.0.0
  yaml: ^3.1.1
  path: ^1.8.0
  path_provider: ^2.0.2
  sqflite: ^2.2.6
  sqflite_common_ffi: ^2.2.2
  sqlite3_flutter_libs: ^0.5.13
  hotkey_manager: ^0.1.7
  window_manager: ^0.3.1
  fluttertoast: ^8.2.1
  emoji_picker_flutter: ^1.5.2
  http: ^0.13.3
  json_schema2: ^2.0.3+7
  sn_progress_dialog: ^1.1.3
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/schemas/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/fclipboard.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/fclipboard-transparent.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/fclipboard-transparent.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/fclipboard-transparent.png"
