name: fclipboard
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0-339.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fuzzy: <1.0.0
  yaml: ^3.1.1
  path: ^1.8.0
  path_provider: ^2.0.2
  sqflite: ^2.2.6
  sqflite_common_ffi: ^2.2.2
  hotkey_manager: ^0.1.7
  window_manager: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"

flutter:
  uses-material-design: true
  assets:
    - assets/commands/
    - assets/images/
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/fclipboard.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/fclipboard.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/fclipboard.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/fclipboard.png"
