openapi: "3.0.2"
info:
  title: "Subscription API"
  description: "The Subscription API allows you to subscribe to events that happen in the system."
  version: "1.0.0"
paths:
  /v1/{uid}/subscriptions:
    get:
      summary: "List subscriptions"
      description: "List subscriptions"
      operationId: "listSubscriptions"
      parameters:
        - name: "uid"
          in: "path"
          description: "The user id"
          required: true
          schema:
            type: "string"
            example: "shopppon@gmail.com"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubscriptionListResp"
        500:
          description: "Internal Server Error"
      tags:
        - subscription
    post:
      summary: "Create a subscription"
      description: "Create a subscription"
      operationId: "createSubscription"
      parameters:
        - name: "uid"
          in: "path"
          description: "The user id"
          required: true
          schema:
            type: "string"
            example: "shopppon@gmail.com"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubscriptionPostReq"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubscriptionPostResp"
        500:
          description: "Internal Server Error"
      tags:
        - subscription
  /v1/{uid}/subscriptions/{sid}/push:
    post:
      summary: "Push a subscription"
      description: "Push a subscription"
      operationId: "pushSubscription"
      parameters:
        - name: "uid"
          in: "path"
          description: "The user id"
          required: true
          schema:
            type: "string"
            example: "shopppon@gmail.com"
        - name: "sid"
          in: "path"
          description: "The subscription id"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubscriptionPushReq"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubscriptionPushResp"
        500:
          description: "Internal Server Error"
      tags:
        - subscription
  /v1/{uid}/subscriptions/{sid}/pull:
    get:
      summary: "Pull a subscription"
      description: "Pull a subscription"
      operationId: "pullSubscription"
      parameters:
        - name: "uid"
          in: "path"
          description: "The user id"
          required: true
          schema:
            type: "string"
            example: "shopppon@gmail.com"
        - name: "sid"
          in: "path"
          description: "The subscription id"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubscriptionPullResp"
        500:
          description: "Internal Server Error"
      tags:
        - subscription
  /v1/{uid}/categories:
    post:
      summary: "Create a category"
      description: "Create a category"
      operationId: "createCategory"
      parameters:
        - name: "uid"
          in: "path"
          description: "The user id"
          required: true
          schema:
            type: "string"
            example: "shopppon@gmail.com"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CategoryPostReq"
      responses:
        204:
          description: "No Content"
        500:
          description: "Internal Server Error"
      tags:
        - category
  /v1/{uid}/entries:
    get:
      summary: "List entries"
      description: "List entries"
      operationId: "listEntries"
      parameters:
        - name: "uid"
          in: "path"
          description: "The user id"
          required: true
          schema:
            type: "string"
            example: "shopppon@gmail.com"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EntryListResp"
        500:
          description: "Internal Server Error"
      tags:
        - entry
    post:
      summary: "Create an entry"
      description: "Create an entry"
      operationId: "createEntry"
      parameters:
        - name: "uid"
          in: "path"
          description: "The user id"
          required: true
          schema:
            type: "string"
            example: "shopppon@gmail.com"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EntryPostReq"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EntryPostResp"
        500:
          description: "Internal Server Error"
      tags:
        - entry
  /v1/{uid}/entries/{eid}:
    patch:
      summary: "Update an entry"
      description: "Update an entry"
      operationId: "updateEntry"
      parameters:
        - name: "uid"
          in: "path"
          description: "The user id"
          required: true
          schema:
            type: "string"
            example: "shopppon@gmail.com"
        - name: "eid"
          in: "path"
          description: "The entry id"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EntryPatchReq"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EntryPatchResp"
        500:
          description: "Internal Server Error"
      tags:
        - entry
    delete:
      summary: "Delete an entry"
      description: "Delete an entry"
      operationId: "deleteEntry"
      parameters:
        - name: "uid"
          in: "path"
          description: "The user id"
          required: true
          schema:
            type: "string"
            example: "shopppon@gmail.com"
        - name: "eid"
          in: "path"
          description: "The entry id"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      responses:
        204:
          description: "No Content"
        500:
          description: "Internal Server Error"
      tags:
        - entry
components:
  schemas:
    Entry:
      type: "object"
      properties:
        name:
          type: "string"
          description: "The name of the entry"
          example: "Foo Bar Baz"
        content:
          type: "string"
          description: "The content of the entry"
          example: "foo bar baz"
        category:
          type: "string"
          description: "The category of the entry"
          example: "news"
        counter:
          type: "integer"
          description: "The counter of the entry"
          example: 1
        parameters:
          type: "array"
          items:
            type: "object"
            properties:
              name:
                type: "string"
                description: "The name of the parameter"
                example: "foo"
              initial:
                type: "string"
                description: "The initial value of the parameter"
                example: "bar"
              required:
                type: "boolean"
                description: "Whether the parameter is required"
                example: true
              description:
                type: "string"
                description: "The description of the parameter"
                example: "Foo Bar Baz"
    EntryListResp:
      type: "object"
      properties:
        entries:
          type: "array"
          items:
            $ref: "#/components/schemas/Entry"
    EntryPostReq:
      type: "object"
      properties:
        entry:
          $ref: "#/components/schemas/Entry"
    EntryPostResp:
      type: "object"
      properties:
        entry:
          $ref: "#/components/schemas/Entry"
    EntryPatchReq:
      type: "object"
      properties:
        entry:
          $ref: "#/components/schemas/Entry"
    EntryPatchResp:
      type: "object"
      properties:
        entry:
          $ref: "#/components/schemas/Entry"
    CategoryPostReq:
      type: "object"
      properties:
        category:
          type: "object"
          properties:
            name:
              type: "string"
              description: "The name of the category"
              example: "news"
            description:
              type: "string"
              description: "The description of the category"
              example: "News"
            is_private:
              type: boolean
              description: "Whether the category is private"
              example: true
            icon:
              type: "string"
              description: "The icon of the category"
    Subscription:
      type: "object"
      required:
        - "id"
        - "categories"
      properties:
        id:
          type: "string"
          format: "uuid"
          example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
        name:
          type: "string"
          description: "The name of the subscription"
          example: "subscription name"
        url:
          type: "string"
          description: "The url of the subscription"
          example: "https://example.com"
        public:
          type: boolean
          description: "whether the subscription is public"
          example: true
        categories:
          type: "array"
          items:
            type: "string"
            description: "The categories of the subscription"
            example: "news"
        created_at:
          type: "string"
          format: "date-time"
          example: "2019-11-29T09:42:31.123Z"
    SubscriptionListResp:
      type: "object"
      properties:
        subscriptions:
          type: "array"
          items:
            $ref: "#/components/schemas/Subscription"
    SubscriptionPostReq:
      type: "object"
      properties:
        subscription:
          type: "object"
          properties:
            name:
              type: "string"
              description: "The name of the subscription"
              example: "Foo Bar Baz"
            description:
              type: "string"
              description: "The description of the subscription"
              example: "Foo Bar Baz"
            categories:
              type: "array"
              items:
                type: "string"
                description: "The categories of the subscription"
                example: "news"
            public:
              type: boolean
              description: "whether the subscription is public"
              example: true
    SubscriptionPostResp:
      type: "object"
      properties:
        subscription:
          $ref: "#/components/schemas/Subscription"
    SubscriptionPushReq:
      type: "object"
      properties:
        entries:
          type: "array"
          items:
            $ref: "#/components/schemas/Entry"
    SubscriptionPushResp:
      type: "object"
      properties:
        sid:
          type: string
          description: "subscription id"
          example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
    SubscriptionPullResp:
      type: "object"
      properties:
        entries:
          type: "array"
          items:
            $ref: "#/components/schemas/Entry"
