openapi: "3.0.2"
info:
  title: "Subscription API"
  description: "The Subscription API allows you to subscribe to events that happen in the system."
  version: "1.0.0"
paths:
  /v1/{uid}/subscriptions:
    get:
      summary: "List subscriptions"
      description: "List subscriptions"
      operationId: "listSubscriptions"
      parameters:
        - name: "uid"
          in: "path"
          description: "The user id"
          required: true
          schema:
            type: "string"
            example: "shopppon@gmail.com"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubscriptionListResp"
        500:
          description: "Internal Server Error"
    post:
      summary: "Create a subscription"
      description: "Create a subscription"
      operationId: "createSubscription"
      parameters:
        - name: "uid"
          in: "path"
          description: "The user id"
          required: true
          schema:
            type: "string"
            example: "shopppon@gmail.com"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubscriptionPostReq"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubscriptionPostResp"
        500:
          description: "Internal Server Error"
  /v1/{uid}subscriptions/{sid}/push:
    post:
      summary: "Push a subscription"
      description: "Push a subscription"
      operationId: "pushSubscription"
      parameters:
        - name: "uid"
          in: "path"
          description: "The user id"
          required: true
          schema:
            type: "string"
            example: "shopppon@gmail.com"
        - name: "sid"
          in: "path"
          description: "The subscription id"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubscriptionPushReq"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subscription"
        500:
          description: "Internal Server Error"
  /v1/{uid}/subscriptions/{sid}/pull:
    get:
      summary: "Pull a subscription"
      description: "Pull a subscription"
      operationId: "pullSubscription"
      parameters:
        - name: "uid"
          in: "path"
          description: "The user id"
          required: true
          schema:
            type: "string"
            example: "shopppon@gmail.com"
        - name: "sid"
          in: "path"
          description: "The subscription id"
          required: true
          schema:
            type: "string"
            format: "uuid"
            example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubscriptionPullResp"
        500:
          description: "Internal Server Error"
components:
  schemas:
    Entry:
      type: "object"
      properties:
        name:
          type: "string"
          description: "The name of the entry"
          example: "Foo Bar Baz"
        content:
          type: "string"
          description: "The content of the entry"
          example: "foo bar baz"
        category:
          type: "string"
          description: "The category of the entry"
          example: "news"
        counter:
          type: "integer"
          description: "The counter of the entry"
          example: 1
        parameters:
          type: "array"
          items:
            type: "object"
            properties:
              name:
                type: "string"
                description: "The name of the parameter"
                example: "foo"
              initial:
                type: "string"
                description: "The initial value of the parameter"
                example: "bar"
              required:
                type: "boolean"
                description: "Whether the parameter is required"
                example: true
              description:
                type: "string"
                description: "The description of the parameter"
                example: "Foo Bar Baz"
    Subscription:
      type: "object"
      required:
        - "id"
        - "categories"
      properties:
        id:
          type: "string"
          format: "uuid"
          example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
        url:
          type: "string"
          description: "The url of the subscription"
          example: "https://example.com"
        categories:
          type: "array"
          items:
            type: "string"
            description: "The categories of the subscription"
            example: "news"
        created_at:
          type: "string"
          format: "date-time"
          example: "2019-11-29T09:42:31.123Z"
    SubscriptionListResp:
      type: "object"
      properties:
        subscriptions:
          type: "array"
          items:
            $ref: "#/components/schemas/Subscription"
    SubscriptionPostReq:
      type: "object"
      properties:
        subscription:
          type: "object"
          properties:
            name:
              type: "string"
              description: "The name of the subscription"
              example: "Foo Bar Baz"
            description:
              type: "string"
              description: "The description of the subscription"
              example: "Foo Bar Baz"
            categories:
              type: "array"
              items:
                type: "string"
                description: "The categories of the subscription"
                example: "news"
    SubscriptionPostResp:
      type: "object"
      properties:
        subscription:
          $ref: "#/components/schemas/Subscription"
    SubscriptionPushReq:
      type: "object"
      properties:
        entries:
          type: "array"
          items:
            $ref: "#/components/schemas/Entry"
    SubscriptionPullResp:
      type: "object"
      properties:
        entries:
          type: "array"
          items:
            $ref: "#/components/schemas/Entry"
