apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider
  namespace: fclipboard
spec:
  selector:
    matchLabels:
      application: fclipboard
      component: provider
  template:
    metadata:
      labels:
        application: fclipboard
        component: provider
    spec:
      containers:
        - image: shoppon/fclipboard-provider:latest
          name: provider
          # command: ["/bin/bash", "-c", "--"]
          # args: ["while true; do sleep 30; done;"]
          command:
            [
              "fclipboard-provider",
              "/opt/fclipboard/settings.toml",
            ]
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - mountPath: /opt/fclipboard/settings.toml
              name: config-file
              subPath: settings.toml
              readOnly: true
      volumes:
        - name: config-file
          configMap:
            name: provider-etc
